/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veritabanı;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arfzbk
 */
public class aracBakımJF extends javax.swing.JFrame {
    public void kullanici(String kullanici){
    Veritabanı db=new Veritabanı();
   
     
}
Veritabanı db=new Veritabanı();
    /**
     * Creates new form arac_bakımJF
     */
    public aracBakımJF() {
        initComponents();
        db.bakımdakiAracListele(jt_arac_bakım);
        girisJF giris=new girisJF();
        System.out.println(giris.kullanici);
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_arac_bakım = new javax.swing.JTable();
        jb_yeniBakim = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jl_plaka = new javax.swing.JLabel();
        tf_plaka = new javax.swing.JTextField();
        tf_musteri = new javax.swing.JTextField();
        tf_durum = new javax.swing.JTextField();
        jl_musteri = new javax.swing.JLabel();
        jl_durum = new javax.swing.JLabel();
        jb_bakımdanCıkar = new javax.swing.JButton();
        jb_durumGuncelle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jl_isim = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jt_arac_bakım.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Araç Plakası", "Bakım Id", "Bakım Türü", "Giris Tarihi", "Bakım Nedeni", "Bakım Durumu", "Müşteri No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_arac_bakım.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_arac_bakımMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_arac_bakım);

        jb_yeniBakim.setBackground(new java.awt.Color(153, 255, 153));
        jb_yeniBakim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veritabanı/kayıt.png"))); // NOI18N
        jb_yeniBakim.setText("Yeni Bakım Ekle");
        jb_yeniBakim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_yeniBakim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_yeniBakimActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Düzenle veya Sil"));

        jl_plaka.setText("Plaka:");

        tf_musteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_musteriActionPerformed(evt);
            }
        });

        tf_durum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_durumActionPerformed(evt);
            }
        });

        jl_musteri.setText("Müşteri No:");

        jl_durum.setText("Durum:");

        jb_bakımdanCıkar.setBackground(new java.awt.Color(255, 102, 102));
        jb_bakımdanCıkar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veritabanı/stop.png"))); // NOI18N
        jb_bakımdanCıkar.setText("Bakımdan Çıkar");
        jb_bakımdanCıkar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_bakımdanCıkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_bakımdanCıkarActionPerformed(evt);
            }
        });

        jb_durumGuncelle.setBackground(new java.awt.Color(255, 255, 153));
        jb_durumGuncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veritabanı/sync.png"))); // NOI18N
        jb_durumGuncelle.setText("Bakım Durum Güncelleme");
        jb_durumGuncelle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_durumGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_durumGuncelleActionPerformed(evt);
            }
        });

        jLabel1.setText("Hatalı Kayıt Var İse:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_musteri)
                    .addComponent(jl_durum, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_plaka)
                    .addComponent(tf_musteri, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tf_durum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_durumGuncelle))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jb_bakımdanCıkar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_musteri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_musteri))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_durum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_durum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_durumGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_bakımdanCıkar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jl_isim.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jl_isim.setForeground(new java.awt.Color(255, 255, 255));
        jl_isim.setText("Bakımdaki Araçlar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_isim, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jl_isim)
                .addGap(25, 25, 25))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veritabanı/reply.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("  x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("  -");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_yeniBakim, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_yeniBakim, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1024, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_yeniBakimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_yeniBakimActionPerformed
        yeniBakımEkleJF ybe=new  yeniBakımEkleJF();
        ybe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_yeniBakimActionPerformed

    private void jb_durumGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_durumGuncelleActionPerformed
        try {
            DefaultTableModel model=(DefaultTableModel) jt_arac_bakım.getModel();
        db.aracBakımDurumGuncelle(tf_plaka.getText(),Integer.parseInt(tf_musteri.getText()), tf_durum.getText());
        model.getDataVector().clear();
db.bakımdakiAracListele(jt_arac_bakım);
JOptionPane.showMessageDialog(this,"Bakım Güncellendi");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Bakım Güncellenemedi");
        }
        


    }//GEN-LAST:event_jb_durumGuncelleActionPerformed

    private void tf_durumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_durumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_durumActionPerformed

    private void tf_musteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_musteriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_musteriActionPerformed

    private void jt_arac_bakımMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_arac_bakımMouseClicked
tf_durum.setText("");
        DefaultTableModel model=(DefaultTableModel) jt_arac_bakım.getModel();
        int secili_row=jt_arac_bakım.getSelectedRow();
        tf_plaka.setText(model.getValueAt(secili_row, 0).toString());
        tf_musteri.setText(model.getValueAt(secili_row,6).toString());
    }//GEN-LAST:event_jt_arac_bakımMouseClicked

    private void jb_bakımdanCıkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_bakımdanCıkarActionPerformed
      int dialogButton = JOptionPane.YES_NO_OPTION;
            JOptionPane.showConfirmDialog (null, "Emin misiniz?","Dikkat", dialogButton);
            if(dialogButton == JOptionPane.YES_OPTION) {
                DefaultTableModel model=(DefaultTableModel) jt_arac_bakım.getModel();
       int secili_row=jt_arac_bakım.getSelectedRow();
        if (tf_plaka.getText().equals("")) {
            JOptionPane.showMessageDialog(this,"Lütfen Plaka Seçin");
            return;
        }
        db.bakımdanCıkar(Integer.parseInt(model.getValueAt(secili_row,6).toString()),Integer.parseInt(model.getValueAt(secili_row,1).toString()), tf_plaka.getText());
        model.getDataVector().clear();
        db.bakımdakiAracListele(jt_arac_bakım);
            if(dialogButton == JOptionPane.NO_OPTION) {
                  remove(dialogButton);
                }
              }
        
        
    }//GEN-LAST:event_jb_bakımdanCıkarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         anaekranJF home=new anaekranJF();
       home.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       this.setState(aracBakımJF.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aracBakımJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aracBakımJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aracBakımJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aracBakımJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aracBakımJF().setVisible(true);
            }
        });
    }
    private void seticon(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ikon.png")));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_bakımdanCıkar;
    private javax.swing.JButton jb_durumGuncelle;
    private javax.swing.JButton jb_yeniBakim;
    private javax.swing.JLabel jl_durum;
    private javax.swing.JLabel jl_isim;
    private javax.swing.JLabel jl_musteri;
    private javax.swing.JLabel jl_plaka;
    private javax.swing.JTable jt_arac_bakım;
    private javax.swing.JTextField tf_durum;
    private javax.swing.JTextField tf_musteri;
    private javax.swing.JTextField tf_plaka;
    // End of variables declaration//GEN-END:variables
}
